version: "3"
services:
  app:
    container_name: "poetry-example"
    build: .
    user: root
    volumes:
      - ./:/workspace
    ports:
      - 8881:8881
    
    command: jupyter notebook --port=8881 --ip=0.0.0.0 --allow-root
